### ISSUE TITLE
http://pjdietz.com/2016/08/28/nginx-in-docker-without-root.html

### ISSUE THREAD

**Issue by dalu** [pjdietz/pjdietz.github.io#1]
Please read 
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#root-inside-location-block

Since you're not allowing or supporting comments

![duty_calls](https://imgs.xkcd.com/comics/duty_calls.png)

**Comment by pjdietz** [comment]
I'd prefer to keep the examples closer to the config files shipped with the Docker images. Also, this is really orthogonal to the post.

**Comment by dalu** [comment]
Seems like you didn't understand the question. It's ok, not everyone is fit for being a sysadmin.

**Comment by pjdietz** [comment]
Maybe try a less juvenile and snarky tone. Until then, I have no interest in trolls.
